# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
trigger:
  - main

resources:
  pipelines:
  - pipeline: gustatia # Name of the pipeline resource.
    source: gustatia-ci # The name of the pipeline referenced by this pipeline resource.
    trigger: 
      branches:
        include: 
        - main

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: $(DISTRIBUTION_CERT)
    certPwd: $(DISTRIBUTION_CERT_PASSWORD)
    keychain: 'temp'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: $(PROVISIONING_PROFILE)
- task: Xcode@5
  inputs:
    actions: 'clean'
    scheme: $(Scheme)
    sdk: $(SDK)
    configuration: $(Configuration)
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
    packageApp: true
    signingOption: manual
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    destinationPlatformOption: iOS
    destinationTypeOption: simulators
    destinationSimulators: 'iPhone 14 Pro Max'
    useXcpretty: true
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
